version: '2'
services:
  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./src/db/migrations:/flyway/sql
      - ./flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
    networks:
      local:
        ipv4_address: 112.10.0.2

  postgres:
    image: postgres:10
    restart: always
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      local:
        ipv4_address: 112.10.0.3

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 112.10.0.0/16
          gateway: 112.10.0.1
