service: notifier

provider:
  name: aws
  runtime: nodejs12.x

functions:
  # Users
  register:
    handler: src/functions/users/register/index.handler
    events:
      - http:
          method: POST
          path: /users/register

  login:
    handler: src/functions/users/login/index.handler
    events:
      - http:
          method: POST
          path: /users/login

  get-user:
    handler: src/functions/users/get/index.handler
    events:
      - http:
          method: GET
          path: /users/{id}
          request:
            parameters:
              paths:
                id: true

  list-users:
    handler: src/functions/users/list/index.handler
    events:
      - http:
          method: GET
          path: /users

plugins:
  # - serverless-offline-sns
  - serverless-dotenv-plugin
  - serverless-offline
