service: notifier-backend
useDotenv: true

provider:
  name: aws
  region: ${env:PROVIDER_REGION}
  stage: ${env:PROVIDER_STAGE}
  stackName: ${env:STACK_PREFIX}-${self:provider.stage}-backend
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

custom:
  serverless-offline-sns:
    port: 4002
    host: localhost
    endpoint: http://localhost:4002
    debug: false

functions:
  - ${file(yml/lambdas.yml)}

resources:
  - ${file(yml/gateway.yml)}

plugins:
  - serverless-offline-sns
  - serverless-dotenv-plugin
  - serverless-offline
